// Code generated by fabrica codegen init. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/alexlovelltroy/fabrica/pkg/codegen"
	"github.com/openchami/fru-service/pkg/resources/fru"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica codegen init' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&fru.FRU{}); err != nil {
		return fmt.Errorf("failed to register FRU: %w", err)
	}

	return nil
}
