// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package main

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/openchami/fabrica/pkg/annotations"
)

func TestValidateDiscoveredResourceAnnotations_joins_independent_source_errors(t *testing.T) {
	// Given
	dir := t.TempDir()
	firstPath := filepath.Join(dir, "token.go")
	secondPath := filepath.Join(dir, "device.go")
	writeMalformedAnnotationFile(t, firstPath, "Token")
	writeMalformedAnnotationFile(t, secondPath, "Device")

	// When
	err := validateDiscoveredResourceAnnotations([]discoveredResource{
		{Name: "Token", SourcePath: firstPath},
		{Name: "Device", SourcePath: secondPath},
	}, "ent", "sqlite")

	// Then
	if err == nil {
		t.Fatal("validateDiscoveredResourceAnnotations() error = nil")
	}
	joined, ok := err.(interface{ Unwrap() []error })
	if !ok || len(joined.Unwrap()) != 2 {
		t.Fatalf("joined errors = %#v, want two", err)
	}
	for _, expected := range []string{firstPath, secondPath, "sensitve"} {
		if !strings.Contains(err.Error(), expected) {
			t.Errorf("joined error missing %q: %v", expected, err)
		}
	}
}

func TestGenerateCommand_annotation_preflight_failure_preserves_existing_schema_output(t *testing.T) {
	// Given
	root := t.TempDir()
	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(originalDir); err != nil {
			t.Errorf("restore working directory: %v", err)
		}
	})
	if err := os.Chdir(root); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("go.mod", []byte("module example.com/preflight\n\ngo 1.23\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	config := "project:\n  name: preflight\n  module: example.com/preflight\nfeatures:\n  storage:\n    enabled: true\n    type: ent\n    db_driver: sqlite\n"
	if err := os.WriteFile(".fabrica.yaml", []byte(config), 0o600); err != nil {
		t.Fatal(err)
	}
	apisConfig := "groups:\n  - name: test.example\n    storageVersion: v1\n    versions: [v1]\n    resources: [Token]\n"
	if err := os.WriteFile("apis.yaml", []byte(apisConfig), 0o600); err != nil {
		t.Fatal(err)
	}
	resourcePath := filepath.Join("apis", "test.example", "v1", "token_types.go")
	if err := os.MkdirAll(filepath.Dir(resourcePath), 0o755); err != nil {
		t.Fatal(err)
	}
	const source = `package v1

// +fabrica:resource
type Token struct {
	APIVersion string
	Kind string
	Metadata struct{}
	Spec TokenSpec
}
type TokenSpec struct {
	// +fabrica:field:sensitve
	Value string
}`
	if err := os.WriteFile(resourcePath, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	schemaPath := filepath.Join("internal", "storage", "ent", "schema", "token.go")
	if err := os.MkdirAll(filepath.Dir(schemaPath), 0o755); err != nil {
		t.Fatal(err)
	}
	before := []byte("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype Token struct{}\n")
	if err := os.WriteFile(schemaPath, before, 0o644); err != nil {
		t.Fatal(err)
	}
	command := newGenerateCommand()
	command.SetArgs([]string{"--force", "--storage"})

	// When
	err = command.Execute()

	// Then
	if !errors.Is(err, annotations.ErrAnnotationParse) {
		t.Fatalf("generate error = %v, want annotation parse error", err)
	}
	after, readErr := os.ReadFile(schemaPath)
	if readErr != nil || string(after) != string(before) {
		t.Fatalf("preflight changed schema output = %q, %v", after, readErr)
	}
	if _, statErr := os.Stat(filepath.Join("pkg", "resources", "register_generated.go")); !os.IsNotExist(statErr) {
		t.Fatalf("registration generation ran before preflight: %v", statErr)
	}
}

func writeMalformedAnnotationFile(t *testing.T, path, resourceName string) {
	t.Helper()
	source := `package fixture

// +fabrica:resource
type RESOURCE struct { Spec RESOURCESpec }
type RESOURCESpec struct {
	// +fabrica:field:sensitve
	Value string
}`
	source = strings.ReplaceAll(source, "RESOURCE", resourceName)
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatalf("write malformed annotation source: %v", err)
	}
}
