// SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEnsureCustomStorageHasNoGeneratedArtifacts_AllowsFreshCustomStorage(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "internal", "storage"), 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "internal", "storage", "storage.go"), []byte("package storage\n"), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	if err := ensureCustomStorageHasNoGeneratedArtifacts(root); err != nil {
		t.Fatalf("fresh custom storage rejected: %v", err)
	}
}

func TestEnsureCustomStorageHasNoGeneratedArtifacts_AllowsProjectOwnedFilesAtGeneratedPaths(t *testing.T) {
	root := t.TempDir()
	projectFiles := map[string]string{
		filepath.Join("internal", "storage", "storage_generated.go"): "package storage\n\nfunc LoadThing() {}\n",
		filepath.Join("internal", "storage", "ent", "repository.go"): "package ent\n\nfunc OpenRepository() {}\n",
		filepath.Join("cmd", "server", "export.go"):                  "package main\n\nfunc newExportCommand() {}\n",
	}

	for rel, content := range projectFiles {
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("MkdirAll %s: %v", rel, err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatalf("WriteFile %s: %v", rel, err)
		}
	}

	if err := ensureCustomStorageHasNoGeneratedArtifacts(root); err != nil {
		t.Fatalf("project-owned custom storage files rejected: %v", err)
	}
}

func TestEnsureCustomStorageHasNoGeneratedArtifacts_RejectsStaleGeneratedStorage(t *testing.T) {
	root := t.TempDir()
	staleFile := filepath.Join(root, "internal", "storage", "storage_generated.go")
	staleEntDir := filepath.Join(root, "internal", "storage", "ent")
	staleEntFile := filepath.Join(staleEntDir, "client.go")
	if err := os.MkdirAll(filepath.Dir(staleFile), 0o755); err != nil {
		t.Fatalf("MkdirAll storage: %v", err)
	}
	if err := os.WriteFile(staleFile, []byte("// Code generated by Fabrica test. DO NOT EDIT.\npackage storage\n"), 0o644); err != nil {
		t.Fatalf("WriteFile storage_generated.go: %v", err)
	}
	if err := os.MkdirAll(staleEntDir, 0o755); err != nil {
		t.Fatalf("MkdirAll ent: %v", err)
	}
	if err := os.WriteFile(staleEntFile, []byte("// Code generated by Fabrica test. DO NOT EDIT.\npackage ent\n"), 0o644); err != nil {
		t.Fatalf("WriteFile ent/client.go: %v", err)
	}

	err := ensureCustomStorageHasNoGeneratedArtifacts(root)
	if err == nil {
		t.Fatalf("expected stale generated artifacts to be rejected")
	}
	message := err.Error()
	for _, want := range []string{
		filepath.Join("internal", "storage", "storage_generated.go"),
		filepath.Join("internal", "storage", "ent"),
		"remove these generated artifacts or replace them with project-owned storage before regenerating",
	} {
		if !strings.Contains(message, want) {
			t.Fatalf("error %q does not contain %q", message, want)
		}
	}
	if _, err := os.Stat(staleFile); err != nil {
		t.Fatalf("stale file should not be removed: %v", err)
	}
	if _, err := os.Stat(staleEntDir); err != nil {
		t.Fatalf("stale Ent dir should not be removed: %v", err)
	}
}
