// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package main

import (
	"go/format"
	"strings"
	"testing"

	configpkg "github.com/openchami/fabrica/internal/config"
)

func TestRegistrationGeneratorsIncludeGeneratedSPDXHeader(t *testing.T) {
	oldVersion := version
	version = "test-version"
	defer func() {
		version = oldVersion
	}()

	apisConfig := configpkg.DefaultAPIsConfig("example.fabrica.dev", "v1", []string{"v1"})

	for name, content := range map[string]string{
		"non-versioned": generateRegistrationCode("example.com/test", []discoveredResource{
			{Name: "Device", SourcePath: "pkg/resources/device/device.go"},
		}),
		"versioned": generateVersionedRegistrationCode("example.com/test", apisConfig, []discoveredResource{
			{Name: "Device", SourcePath: "apis/example.fabrica.dev/v1/device_types.go"},
		}),
	} {
		if !strings.Contains(content, "Code generated by Fabrica test-version. DO NOT EDIT.") {
			t.Fatalf("%s registration missing generated banner", name)
		}
		if !strings.Contains(content, "Copyright © ") {
			t.Fatalf("%s registration missing copyright header", name)
		}
		// If the line below includes a full header, it will flag the reuse test as a malformed header and fail.
		if !strings.Contains(content, "PDX-License-Identifier: MIT") {
			t.Fatalf("%s registration missing SPDX license header", name)
		}
	}
}

func TestRegistrationGeneratorsProduceGofmtStableOutput(t *testing.T) {
	apisConfig := configpkg.DefaultAPIsConfig("example.fabrica.dev", "v1", []string{"v1"})

	for name, content := range map[string]string{
		"non-versioned": generateRegistrationCode("github.com/openchami/boot-service", []discoveredResource{
			{Name: "Node", SourcePath: "pkg/resources/node/node.go"},
			{Name: "BMC", SourcePath: "pkg/resources/bmc/bmc.go"},
		}),
		"versioned": generateVersionedRegistrationCode("github.com/openchami/boot-service", apisConfig, []discoveredResource{
			{Name: "Node", SourcePath: "apis/example.fabrica.dev/v1/node_types.go"},
			{Name: "BMC", SourcePath: "apis/example.fabrica.dev/v1/bmc_types.go"},
		}),
	} {
		_, err := format.Source([]byte(content))
		if err != nil {
			t.Fatalf("%s registration should be gofmt-able: %v", name, err)
		}
	}
}

func TestRegistrationGenerators_preserve_source_path_for_automatic_attachment(t *testing.T) {
	// Given
	apisConfig := configpkg.DefaultAPIsConfig("example.fabrica.dev", "v1", []string{"v1"})
	const sourcePath = "apis/example.fabrica.dev/v1/device_types.go"

	// When
	content := generateVersionedRegistrationCode("example.com/test", apisConfig, []discoveredResource{
		{Name: "Device", SourcePath: sourcePath},
	})

	// Then
	want := `gen.RegisterResourceFromSource(&v1.Device{}, "` + sourcePath + `")`
	if !strings.Contains(content, want) {
		t.Fatalf("registration missing exact source attachment %q\n%s", want, content)
	}
	for _, obsolete := range []string{"ParseResourceAnnotations", "SetResourceAnnotations"} {
		if strings.Contains(content, obsolete) {
			t.Errorf("normal registration still requires %s\n%s", obsolete, content)
		}
	}
}

func TestGenerateRunner_prepares_annotations_before_templates(t *testing.T) {
	// Given
	code := generateRunnerCode("/project", "example.com/test", "cmd/server", "main", true, true, true, false, false, "ent")

	// When
	registrationIndex := strings.Index(code, "resources.RegisterAllResources(gen)")
	prepareIndex := strings.Index(code, "gen.PrepareResourceAnnotations()")
	templateIndex := strings.Index(code, "gen.LoadTemplates()")

	// Then
	if registrationIndex < 0 || prepareIndex < 0 || templateIndex < 0 {
		t.Fatalf("runner missing registration, preparation, or template phase\n%s", code)
	}
	if registrationIndex >= prepareIndex || prepareIndex >= templateIndex {
		t.Fatalf("runner phase order registration=%d prepare=%d templates=%d", registrationIndex, prepareIndex, templateIndex)
	}
}
