// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func TestGeneratedConditionalMiddlewareBehavior(t *testing.T) {
	gen := NewGenerator(t.TempDir(), "main", "example.com/test")
	if err := gen.LoadTemplates(); err != nil {
		t.Fatalf("LoadTemplates: %v", err)
	}

	var generated bytes.Buffer
	data := gen.middlewareData("middleware/conditional.go.tmpl")
	if err := gen.Templates["middlewareConditional"].Execute(&generated, data); err != nil {
		t.Fatalf("render conditional middleware: %v", err)
	}

	dir := t.TempDir()
	writeConditionalFixtureFile(t, dir, "go.mod", "module example.com/conditionalfixture\n\ngo 1.26.6\n")
	writeConditionalFixtureFile(t, dir, "conditional_generated.go", generated.String())
	writeConditionalFixtureFile(t, dir, "conditional_generated_test.go", generatedConditionalBehaviorTest)

	cmd := exec.Command("go", "test", "-count=1", ".")
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("test generated conditional middleware: %v\n%s", err, output)
	}
}

func writeConditionalFixtureFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

const generatedConditionalBehaviorTest = `package server

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestGeneratedETagIsStable(t *testing.T) {
	first, err := GenerateETag(map[string]int{"alpha": 1, "beta": 2})
	if err != nil {
		t.Fatalf("GenerateETag(first): %v", err)
	}
	second, err := GenerateETag(map[string]int{"beta": 2, "alpha": 1})
	if err != nil {
		t.Fatalf("GenerateETag(second): %v", err)
	}
	if first != second {
		t.Fatalf("stable ETag mismatch: %q != %q", first, second)
	}
	if len(first) < 2 || first[0] != '"' || first[len(first)-1] != '"' {
		t.Fatalf("ETag = %q, want a quoted strong validator", first)
	}
}

func TestGeneratedReadPrecondition(t *testing.T) {
	etag, err := GenerateETag(map[string]string{"uid": "node-1"})
	if err != nil {
		t.Fatalf("GenerateETag: %v", err)
	}

	matching := httptest.NewRequest(http.MethodGet, "/nodes/node-1", nil)
	matching.Header.Set("If-None-Match", etag)
	matchingResponse := httptest.NewRecorder()
	SetETag(matchingResponse, etag)
	if CheckIfNoneMatch(matchingResponse, matching, etag) {
		t.Fatal("matching If-None-Match should suppress the response body")
	}
	if matchingResponse.Code != http.StatusNotModified {
		t.Fatalf("matching status = %d, want %d", matchingResponse.Code, http.StatusNotModified)
	}
	if got := matchingResponse.Header().Get("ETag"); got != etag {
		t.Fatalf("matching ETag header = %q, want %q", got, etag)
	}

	stale := httptest.NewRequest(http.MethodGet, "/nodes/node-1", nil)
	stale.Header.Set("If-None-Match", ` + "`" + `"stale"` + "`" + `)
	staleResponse := httptest.NewRecorder()
	if !CheckIfNoneMatch(staleResponse, stale, etag) {
		t.Fatal("stale If-None-Match should return the resource")
	}
}

func TestGeneratedMutationPrecondition(t *testing.T) {
	etag, err := GenerateETag(map[string]string{"uid": "node-1"})
	if err != nil {
		t.Fatalf("GenerateETag: %v", err)
	}

	tests := []struct {
		name       string
		ifMatch    string
		wantProceed bool
		wantStatus int
	}{
		{name: "absent header proceeds", wantProceed: true, wantStatus: http.StatusOK},
		{name: "matching header proceeds", ifMatch: etag, wantProceed: true, wantStatus: http.StatusOK},
		{name: "stale header fails", ifMatch: ` + "`" + `"stale"` + "`" + `, wantProceed: false, wantStatus: http.StatusPreconditionFailed},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest(http.MethodPut, "/nodes/node-1", nil)
			if tt.ifMatch != "" {
				req.Header.Set("If-Match", tt.ifMatch)
			}
			response := httptest.NewRecorder()
			if got := CheckIfMatch(response, req, etag); got != tt.wantProceed {
				t.Fatalf("CheckIfMatch() = %v, want %v", got, tt.wantProceed)
			}
			if response.Code != tt.wantStatus {
				t.Fatalf("status = %d, want %d", response.Code, tt.wantStatus)
			}
		})
	}
}
`
