// Copyright © 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/openchami/fabrica/pkg/annotations"
)

type StaleDedicatedSpec struct {
	Value string
}

type StaleDedicated struct {
	Spec StaleDedicatedSpec
}

func TestDedicatedSchemaData_exposes_stable_field_mapping(t *testing.T) {
	// Given
	data, err := buildDedicatedDataFromSource(t, dedicatedShapeSource)
	if err != nil {
		t.Fatalf("build dedicated data: %v", err)
	}

	// When
	fields := make(map[string]dedicatedSchemaField, len(data.Fields))
	for _, field := range data.Fields {
		fields[field.GoName] = field
	}

	// Then
	want := []dedicatedSchemaField{
		{GoName: "Name", JSONName: "name", ColumnName: "spec_name"},
		{GoName: "SpecName", JSONName: "spec_name", ColumnName: "spec_spec_name"},
		{GoName: "Status", JSONName: "status", ColumnName: "spec_status"},
		{GoName: "Metadata", JSONName: "metadata", ColumnName: "spec_metadata"},
	}
	for _, expected := range want {
		got, ok := fields[expected.GoName]
		if !ok {
			t.Errorf("mapping for %s is absent", expected.GoName)
			continue
		}
		if got.GoName != expected.GoName || got.JSONName != expected.JSONName || got.ColumnName != expected.ColumnName {
			t.Errorf("mapping for %s = {%q, %q, %q}, want {%q, %q, %q}",
				expected.GoName, got.GoName, got.JSONName, got.ColumnName,
				expected.GoName, expected.JSONName, expected.ColumnName)
		}
	}
}

func TestDedicatedSchemaData_rejects_duplicate_field_names_with_source(t *testing.T) {
	tests := []struct {
		name   string
		fields string
		want   string
	}{
		{
			name: "duplicate JSON name",
			fields: `
	First string ` + "`json:\"same\"`" + `
	Second string ` + "`json:\"same\"`" + ``,
			want: "duplicate JSON name",
		},
		{
			name: "duplicate normalized column",
			fields: `
	First string ` + "`json:\"fooBar\"`" + `
	Second string ` + "`json:\"foo_bar\"`" + ``,
			want: "duplicate normalized column",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			// Given
			source := `package fixture

// +fabrica:resource
// +fabrica:storage=dedicated
type Duplicate struct { Spec DuplicateSpec }
type DuplicateSpec struct {` + test.fields + `
}
`

			// When
			_, err := buildDedicatedDataFromSource(t, source)

			// Then
			var capabilityErr *annotations.CapabilityError
			if !errors.As(err, &capabilityErr) {
				t.Fatalf("error = %v, want CapabilityError", err)
			}
			if capabilityErr.Filename == "" || capabilityErr.Line == 0 || capabilityErr.FieldName != "Second" {
				t.Errorf("source location = %#v, want Second with file and line", capabilityErr)
			}
			if !strings.Contains(capabilityErr.Message, test.want) {
				t.Errorf("message = %q, want %q", capabilityErr.Message, test.want)
			}
		})
	}
}

func TestGenerateEntSchemas_quarantines_stale_dedicated_schema_on_resolution_error(t *testing.T) {
	// Given
	gen, root, sourcePath := newStaleSchemaGenerator(t)
	if err := gen.GenerateEntSchemas(); err != nil {
		t.Fatalf("generate initial schemas: %v", err)
	}
	schemaPath := filepath.Join(root, "internal", "storage", "ent", "schema", "stalededicated.go")
	genericPath := filepath.Join(root, "internal", "storage", "ent", "schema", "resource.go")
	const genericMarker = "generic output must not be rewritten"
	if err := os.WriteFile(genericPath, []byte(genericMarker), 0o644); err != nil {
		t.Fatalf("mark generic output: %v", err)
	}
	if err := os.WriteFile(sourcePath, []byte(unsupportedStaleDedicatedSource), 0o644); err != nil {
		t.Fatalf("replace source with unsupported field: %v", err)
	}

	// When
	err := gen.GenerateEntSchemas()

	// Then
	if err == nil {
		t.Fatal("generation succeeded for unsupported field")
	}
	if _, statErr := os.Stat(schemaPath); !os.IsNotExist(statErr) {
		t.Fatalf("stale dedicated schema remains active: %v", statErr)
	}
	quarantineRoot := findTransactionArtifactFixture(t, filepath.Dir(schemaPath), transactionRoleQuarantine)
	quarantinePath := filepath.Join(quarantineRoot, "stalededicated.go")
	content, readErr := os.ReadFile(quarantinePath)
	if readErr != nil || !strings.HasPrefix(string(content), "// Code generated by Fabrica") {
		t.Fatalf("quarantined dedicated schema = %q, %v", content, readErr)
	}
	content, readErr = os.ReadFile(genericPath)
	if readErr != nil {
		t.Fatalf("read generic marker: %v", readErr)
	}
	if string(content) != genericMarker {
		t.Errorf("generic output was partially rewritten: %q", content)
	}
}

func buildDedicatedDataFromSource(t *testing.T, source string) (dedicatedSchemaData, error) {
	t.Helper()
	path := filepath.Join(t.TempDir(), "resource.go")
	if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
		t.Fatalf("write source: %v", err)
	}
	name := "DedicatedShape"
	if strings.Contains(source, "type Duplicate struct") {
		name = "Duplicate"
	}
	resolved, err := annotations.ResolveStorageIntent(path, name, annotations.DialectPostgreSQL)
	if err != nil {
		return dedicatedSchemaData{}, err
	}
	return buildDedicatedSchemaData(resolved, 2026)
}

func newStaleSchemaGenerator(t *testing.T) (*Generator, string, string) {
	t.Helper()
	root := t.TempDir()
	sourcePath := filepath.Join(root, "stale_types.go")
	if err := os.WriteFile(sourcePath, []byte(validStaleDedicatedSource), 0o644); err != nil {
		t.Fatalf("write valid source: %v", err)
	}
	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("get working directory: %v", err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(originalDir); err != nil {
			t.Errorf("restore working directory: %v", err)
		}
	})
	if err := os.Chdir(root); err != nil {
		t.Fatalf("change to fixture directory: %v", err)
	}

	gen := NewGenerator(root, "fixture", "example.com/fixture")
	gen.StorageType = "ent"
	gen.DBDriver = "sqlite"
	if err := gen.LoadTemplates(); err != nil {
		t.Fatalf("load templates: %v", err)
	}
	if err := gen.RegisterResourceFromSource(&StaleDedicated{}, sourcePath); err != nil {
		t.Fatalf("register source: %v", err)
	}
	if err := gen.PrepareResourceAnnotations(); err != nil {
		t.Fatalf("prepare annotations: %v", err)
	}
	return gen, root, sourcePath
}

const validStaleDedicatedSource = `package fixture

// +fabrica:resource
// +fabrica:storage=dedicated
type StaleDedicated struct { Spec StaleDedicatedSpec }
type StaleDedicatedSpec struct {
	// +fabrica:field:sensitive
	Value string ` + "`json:\"value\"`" + `
}
`

const unsupportedStaleDedicatedSource = `package fixture

// +fabrica:resource
// +fabrica:storage=dedicated
type StaleDedicated struct { Spec StaleDedicatedSpec }
type StaleDedicatedSpec struct {
	// +fabrica:field:sensitive
	Value map[string]string ` + "`json:\"value\"`" + `
}
`
