// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/openchami/fabrica/pkg/annotations"
)

// recordingEmitter stands in for a service-supplied emitter. It captures what
// it was handed so the tests can assert on the contract, and emits an extra
// file alongside the default one.
type recordingEmitter struct {
	mu       sync.Mutex
	calls    []EmitRequest
	extraDir string
}

func (e *recordingEmitter) Name() string { return "test/recording" }

func (e *recordingEmitter) Emit(req EmitRequest) ([]EmittedFile, error) {
	e.mu.Lock()
	e.calls = append(e.calls, req)
	e.mu.Unlock()

	body := fmt.Sprintf(`package %s

// Code generated by the recording emitter for %s.
const %sMarker = %q
`, "schema", req.Resource.Name, req.Resource.Name, req.Annotations.StorageMode)

	files := []EmittedFile{{Path: req.DefaultPath, Content: []byte(body)}}

	if e.extraDir != "" {
		files = append(files, EmittedFile{
			Path:    filepath.Join(e.extraDir, strings.ToLower(req.Resource.Name)+"_extra.go"),
			Content: []byte("package extra\n\n// generated alongside the schema\n"),
		})
	}

	return files, nil
}

func (e *recordingEmitter) requests() []EmitRequest {
	e.mu.Lock()
	defer e.mu.Unlock()

	return append([]EmitRequest(nil), e.calls...)
}

type emitterFixtureSpec struct {
	Value string `json:"value" validate:"required"`
	Owner string `json:"owner"`
}

type emitterFixture struct {
	Spec emitterFixtureSpec
}

// newDedicatedAnnotations builds a valid dedicated-storage annotation set.
func newDedicatedAnnotations() *annotations.ResourceAnnotations {
	a := annotations.NewResourceAnnotations()
	a.IsResource = true
	a.StorageMode = annotations.StorageModeDedicated

	owner := annotations.NewFieldAnnotations("Owner")
	owner.Size = 253
	a.Fields["Owner"] = owner

	return a
}

// newEmitterGenerator returns a generator rooted in a temp dir, with the
// working directory switched for the duration of the test.
func newEmitterGenerator(t *testing.T) *Generator {
	t.Helper()

	tmpDir := t.TempDir()

	origDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("get working directory: %v", err)
	}
	t.Cleanup(func() {
		if err := os.Chdir(origDir); err != nil {
			t.Errorf("restore working directory: %v", err)
		}
	})
	if err := os.Chdir(tmpDir); err != nil {
		t.Fatalf("change to temp directory: %v", err)
	}

	gen := NewGenerator(tmpDir, "test", "github.com/test/project")
	gen.StorageType = "ent"
	gen.DBDriver = "postgres"

	if err := gen.LoadTemplates(); err != nil {
		t.Fatalf("LoadTemplates failed: %v", err)
	}
	if err := gen.RegisterResource(&emitterFixture{}); err != nil {
		t.Fatalf("RegisterResource failed: %v", err)
	}

	gen.SetResourceAnnotations("emitterFixture", newDedicatedAnnotations())

	return gen
}

// TestCustomEmitterIsInvoked is the core claim of the extension point: a
// service can supply its own emitter for a resource and have it run, without
// modifying fabrica's source.
func TestCustomEmitterIsInvoked(t *testing.T) {
	gen := newEmitterGenerator(t)

	emitter := &recordingEmitter{}
	if err := gen.SetEmitter(EmitterKindEntSchema, emitter); err != nil {
		t.Fatalf("SetEmitter failed: %v", err)
	}

	if err := gen.GenerateEntSchemas(); err != nil {
		t.Fatalf("GenerateEntSchemas failed: %v", err)
	}

	reqs := emitter.requests()
	if len(reqs) != 1 {
		t.Fatalf("emitter called %d times, want 1", len(reqs))
	}

	req := reqs[0]
	if req.Kind != EmitterKindEntSchema {
		t.Errorf("Kind = %q, want %q", req.Kind, EmitterKindEntSchema)
	}
	if req.Resource.Name != "emitterFixture" {
		t.Errorf("Resource.Name = %q, want emitterFixture", req.Resource.Name)
	}
	if req.Annotations == nil || req.Annotations.StorageMode != annotations.StorageModeDedicated {
		t.Fatalf("Annotations = %+v, want dedicated storage", req.Annotations)
	}
	if req.Annotations.Fields["Owner"].Size != 253 {
		t.Error("emitter did not receive the resource's field annotations")
	}
	if req.StorageType != "ent" || req.DBDriver != "postgres" {
		t.Errorf("StorageType/DBDriver = %q/%q, want ent/postgres", req.StorageType, req.DBDriver)
	}
	if req.ModulePath != "github.com/test/project" {
		t.Errorf("ModulePath = %q", req.ModulePath)
	}
	if req.Template == nil {
		t.Error("Template is nil; an emitter must be able to reuse the built-in template")
	}
	if req.Data == nil {
		t.Fatal("Data is nil; an emitter must be able to reuse the built-in template data")
	}
	if _, ok := req.Data["CopyrightYear"]; !ok {
		t.Error("Data is missing the merged common fields (CopyrightYear)")
	}

	wantPath := filepath.Join("internal", "storage", "ent", "schema", "emitterfixture.go")
	if req.DefaultPath != wantPath {
		t.Errorf("DefaultPath = %q, want %q", req.DefaultPath, wantPath)
	}

	// The custom output must actually land on disk, replacing the built-in.
	content, err := os.ReadFile(wantPath)
	if err != nil {
		t.Fatalf("read emitted file: %v", err)
	}
	if !strings.Contains(string(content), "emitterFixtureMarker") {
		t.Errorf("emitted file is not the custom emitter's output:\n%s", content)
	}
	if strings.Contains(string(content), "ent.Schema") {
		t.Error("built-in schema was written despite an override being registered")
	}
}

// TestCustomEmitterCanEmitExtraFiles proves an emitter is not limited to
// replacing the default artifact one-for-one.
func TestCustomEmitterCanEmitExtraFiles(t *testing.T) {
	gen := newEmitterGenerator(t)

	if err := gen.SetEmitter(EmitterKindEntSchema, &recordingEmitter{extraDir: "internal/extra"}); err != nil {
		t.Fatalf("SetEmitter failed: %v", err)
	}
	if err := gen.GenerateEntSchemas(); err != nil {
		t.Fatalf("GenerateEntSchemas failed: %v", err)
	}

	extra := filepath.Join("internal", "extra", "emitterfixture_extra.go")
	if _, err := os.Stat(extra); err != nil {
		t.Fatalf("expected the emitter's extra file at %s: %v", extra, err)
	}
}

// TestProcessWideRegistrationIsUsed covers the path a real project takes: an
// init() in a package the generated codegen runner already imports.
func TestProcessWideRegistrationIsUsed(t *testing.T) {
	emitter := &recordingEmitter{}
	if err := RegisterEmitter(EmitterKindEntSchema, emitter); err != nil {
		t.Fatalf("RegisterEmitter failed: %v", err)
	}
	t.Cleanup(func() { UnregisterEmitter(EmitterKindEntSchema) })

	gen := newEmitterGenerator(t)
	if err := gen.GenerateEntSchemas(); err != nil {
		t.Fatalf("GenerateEntSchemas failed: %v", err)
	}

	if got := len(emitter.requests()); got != 1 {
		t.Fatalf("globally registered emitter called %d times, want 1", got)
	}
}

// TestGeneratorEmitterBeatsGlobalRegistration pins the resolution order.
func TestGeneratorEmitterBeatsGlobalRegistration(t *testing.T) {
	global := &recordingEmitter{}
	if err := RegisterEmitter(EmitterKindEntSchema, global); err != nil {
		t.Fatalf("RegisterEmitter failed: %v", err)
	}
	t.Cleanup(func() { UnregisterEmitter(EmitterKindEntSchema) })

	scoped := &recordingEmitter{}

	gen := newEmitterGenerator(t)
	if err := gen.SetEmitter(EmitterKindEntSchema, scoped); err != nil {
		t.Fatalf("SetEmitter failed: %v", err)
	}
	if err := gen.GenerateEntSchemas(); err != nil {
		t.Fatalf("GenerateEntSchemas failed: %v", err)
	}

	if got := len(scoped.requests()); got != 1 {
		t.Errorf("per-generator emitter called %d times, want 1", got)
	}
	if got := len(global.requests()); got != 0 {
		t.Errorf("global emitter called %d times, want 0", got)
	}
}

// TestBuiltinEmitterUsedWhenNoOverride confirms the default path still runs
// through the interface rather than around it.
func TestBuiltinEmitterUsedWhenNoOverride(t *testing.T) {
	gen := newEmitterGenerator(t)

	if got := gen.emitterFor(EmitterKindEntSchema).Name(); got != "builtin/ent-schema" {
		t.Fatalf("emitterFor returned %q, want builtin/ent-schema", got)
	}

	if err := gen.GenerateEntSchemas(); err != nil {
		t.Fatalf("GenerateEntSchemas failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join("internal", "storage", "ent", "schema", "emitterfixture.go"))
	if err != nil {
		t.Fatalf("read generated schema: %v", err)
	}
	if !strings.Contains(string(content), "ent.Schema") {
		t.Errorf("built-in emitter did not produce an Ent schema:\n%s", content)
	}
}

// TestCustomEmitterCanReuseBuiltinTemplate shows the wrapping case: an emitter
// that renders fabrica's own template and post-processes the result.
func TestCustomEmitterCanReuseBuiltinTemplate(t *testing.T) {
	gen := newEmitterGenerator(t)

	if err := gen.SetEmitter(EmitterKindEntSchema, emitterFunc{
		name: "test/wrapping",
		fn: func(req EmitRequest) ([]EmittedFile, error) {
			base, err := builtinEmitters[EmitterKindEntSchema].Emit(req)
			if err != nil {
				return nil, err
			}
			base[0].Content = append(
				[]byte("// vendor banner\n"),
				base[0].Content...,
			)
			return base, nil
		},
	}); err != nil {
		t.Fatalf("SetEmitter failed: %v", err)
	}

	if err := gen.GenerateEntSchemas(); err != nil {
		t.Fatalf("GenerateEntSchemas failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join("internal", "storage", "ent", "schema", "emitterfixture.go"))
	if err != nil {
		t.Fatalf("read generated schema: %v", err)
	}
	got := string(content)
	if !strings.HasPrefix(got, "// vendor banner") {
		t.Errorf("wrapper banner missing:\n%s", got)
	}
	if !strings.Contains(got, "ent.Schema") {
		t.Errorf("wrapped built-in output missing:\n%s", got)
	}
}

// TestDocumentedDelegatingEmitter exercises the exact pattern documented in
// docs/reference/codegen.md: customize the resources you care about, hand the
// rest back to the built-in via BuiltinEmitter.
func TestDocumentedDelegatingEmitter(t *testing.T) {
	delegating := emitterFunc{
		name: "test/delegating",
		fn: func(req EmitRequest) ([]EmittedFile, error) {
			files, err := BuiltinEmitter(req.Kind).Emit(req)
			if err != nil {
				return nil, err
			}
			if req.Annotations.Migration != annotations.MigrationPolicyAdditiveOnly {
				return files, nil
			}
			banner := fmt.Sprintf("// AUDITED SCHEMA — %s is append-only.\n", req.Resource.Name)
			files[0].Content = append([]byte(banner), files[0].Content...)

			return files, nil
		},
	}

	t.Run("delegates when the resource does not opt in", func(t *testing.T) {
		gen := newEmitterGenerator(t)
		if err := gen.SetEmitter(EmitterKindEntSchema, delegating); err != nil {
			t.Fatalf("SetEmitter failed: %v", err)
		}
		if err := gen.GenerateEntSchemas(); err != nil {
			t.Fatalf("GenerateEntSchemas failed: %v", err)
		}

		content, err := os.ReadFile(filepath.Join("internal", "storage", "ent", "schema", "emitterfixture.go"))
		if err != nil {
			t.Fatalf("read generated schema: %v", err)
		}
		if strings.Contains(string(content), "AUDITED SCHEMA") {
			t.Error("banner applied to a resource that did not opt in")
		}
		if !strings.Contains(string(content), "ent.Schema") {
			t.Error("delegated output is not the built-in schema")
		}
	})

	t.Run("customizes when the resource opts in", func(t *testing.T) {
		gen := newEmitterGenerator(t)

		annots := newDedicatedAnnotations()
		annots.Migration = annotations.MigrationPolicyAdditiveOnly
		gen.SetResourceAnnotations("emitterFixture", annots)

		if err := gen.SetEmitter(EmitterKindEntSchema, delegating); err != nil {
			t.Fatalf("SetEmitter failed: %v", err)
		}
		if err := gen.GenerateEntSchemas(); err != nil {
			t.Fatalf("GenerateEntSchemas failed: %v", err)
		}

		content, err := os.ReadFile(filepath.Join("internal", "storage", "ent", "schema", "emitterfixture.go"))
		if err != nil {
			t.Fatalf("read generated schema: %v", err)
		}
		got := string(content)
		if !strings.HasPrefix(got, "// AUDITED SCHEMA") {
			t.Errorf("banner missing:\n%s", got)
		}
		if !strings.Contains(got, "ent.Schema") {
			t.Errorf("built-in output missing:\n%s", got)
		}
	})
}

func TestBuiltinEmitterUnknownKind(t *testing.T) {
	if e := BuiltinEmitter("no-such-kind"); e != nil {
		t.Errorf("BuiltinEmitter(unknown) = %v, want nil", e)
	}
}

// emitterFunc adapts a function to ResourceEmitter for tests.
type emitterFunc struct {
	name string
	fn   func(EmitRequest) ([]EmittedFile, error)
}

func (e emitterFunc) Name() string                              { return e.name }
func (e emitterFunc) Emit(r EmitRequest) ([]EmittedFile, error) { return e.fn(r) }

// --- Registration errors -----------------------------------------------------

func TestRegisterEmitterRejectsBadInput(t *testing.T) {
	if err := RegisterEmitter(EmitterKindEntSchema, nil); err == nil {
		t.Error("expected an error registering a nil emitter")
	}
	if err := RegisterEmitter("no-such-kind", &recordingEmitter{}); err == nil {
		t.Error("expected an error registering an unknown kind")
	}

	gen := newEmitterGenerator(t)
	if err := gen.SetEmitter(EmitterKindEntSchema, nil); err == nil {
		t.Error("expected an error setting a nil emitter")
	}
	if err := gen.SetEmitter("no-such-kind", &recordingEmitter{}); err == nil {
		t.Error("expected an error setting an unknown kind")
	}
}

func TestKnownEmitterKinds(t *testing.T) {
	kinds := KnownEmitterKinds()
	if len(kinds) == 0 {
		t.Fatal("KnownEmitterKinds returned nothing")
	}

	var found bool
	for _, k := range kinds {
		if k == EmitterKindEntSchema {
			found = true
		}
	}
	if !found {
		t.Errorf("KnownEmitterKinds = %v, missing %q", kinds, EmitterKindEntSchema)
	}
}

// TestEmitterProducingInvalidGoFails ensures a broken emitter surfaces a clear
// error instead of writing unparseable source.
func TestEmitterProducingInvalidGoFails(t *testing.T) {
	gen := newEmitterGenerator(t)

	if err := gen.SetEmitter(EmitterKindEntSchema, emitterFunc{
		name: "test/broken",
		fn: func(req EmitRequest) ([]EmittedFile, error) {
			return []EmittedFile{{Path: req.DefaultPath, Content: []byte("this is not go")}}, nil
		},
	}); err != nil {
		t.Fatalf("SetEmitter failed: %v", err)
	}

	err := gen.GenerateEntSchemas()
	if err == nil {
		t.Fatal("expected an error for invalid generated Go")
	}
	if !strings.Contains(err.Error(), "produced invalid Go") {
		t.Errorf("error = %q, want it to mention invalid Go", err)
	}
}

func TestEmitterEmptyPathFails(t *testing.T) {
	gen := newEmitterGenerator(t)

	if err := gen.SetEmitter(EmitterKindEntSchema, emitterFunc{
		name: "test/nopath",
		fn: func(EmitRequest) ([]EmittedFile, error) {
			return []EmittedFile{{Content: []byte("package x\n")}}, nil
		},
	}); err != nil {
		t.Fatalf("SetEmitter failed: %v", err)
	}

	err := gen.GenerateEntSchemas()
	if err == nil || !strings.Contains(err.Error(), "empty path") {
		t.Fatalf("expected an empty-path error, got %v", err)
	}
}

// TestEmitterErrorIsWrappedWithResource keeps failures diagnosable.
func TestEmitterErrorIsWrappedWithResource(t *testing.T) {
	gen := newEmitterGenerator(t)

	if err := gen.SetEmitter(EmitterKindEntSchema, emitterFunc{
		name: "test/failing",
		fn: func(EmitRequest) ([]EmittedFile, error) {
			return nil, fmt.Errorf("boom")
		},
	}); err != nil {
		t.Fatalf("SetEmitter failed: %v", err)
	}

	err := gen.GenerateEntSchemas()
	if err == nil {
		t.Fatal("expected the emitter's error to propagate")
	}
	for _, want := range []string{"emitterFixture", "test/failing", "boom"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("error %q missing %q", err, want)
		}
	}
}
