// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"bytes"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"text/template"
	"time"
)

func TestTemplateDataIncludesCopyrightYear(t *testing.T) {
	gen := NewGenerator(t.TempDir(), "main", "example.com/test")
	gen.Version = "test"

	resource := ResourceMetadata{
		Name:         "Node",
		PluralName:   "nodes",
		Package:      "example.com/test/pkg/resources/node",
		PackageAlias: "node",
		TypeName:     "*node.Node",
		SpecType:     "node.NodeSpec",
		StatusType:   "node.NodeStatus",
		URLPath:      "/nodes",
		StorageName:  "Node",
	}

	data := gen.templateData(resource, "server/handlers.go.tmpl")
	if got, ok := data["CopyrightYear"].(int); !ok || got != time.Now().UTC().Year() {
		t.Fatalf("templateData CopyrightYear = %v, want %d", data["CopyrightYear"], time.Now().UTC().Year())
	}
}

func TestGlobalAndMiddlewareTemplateDataIncludeCopyrightYear(t *testing.T) {
	gen := NewGenerator(t.TempDir(), "main", "example.com/test")
	gen.Version = "test"

	for name, data := range map[string]map[string]interface{}{
		"global":     gen.globalTemplateData("server/models.go.tmpl"),
		"middleware": gen.middlewareData("middleware/validation.go.tmpl"),
	} {
		if got, ok := data["CopyrightYear"].(int); !ok || got != time.Now().UTC().Year() {
			t.Fatalf("%s CopyrightYear = %v, want %d", name, data["CopyrightYear"], time.Now().UTC().Year())
		}
	}
}

func TestExecuteTemplateBackfillsCommonMetadata(t *testing.T) {
	gen := NewGenerator(t.TempDir(), "main", "example.com/test")
	gen.Version = "test"
	gen.Templates = map[string]*template.Template{
		"copyright": template.Must(template.New("copyright").Parse("{{.Version}}|{{.Template}}|{{.CopyrightYear}}")),
	}

	t.Run("nil data", func(t *testing.T) {
		outputPath := filepath.Join(t.TempDir(), "out.txt")
		if err := gen.executeTemplate("copyright", outputPath, nil); err != nil {
			t.Fatalf("executeTemplate(nil): %v", err)
		}

		gotBytes, err := os.ReadFile(outputPath)
		if err != nil {
			t.Fatalf("ReadFile: %v", err)
		}

		want := strings.Join([]string{"test", "copyright", strconv.Itoa(time.Now().UTC().Year())}, "|")
		if got := strings.TrimSpace(string(gotBytes)); got != want {
			t.Fatalf("executeTemplate(nil) = %q, want %q", got, want)
		}
	})

	t.Run("map data", func(t *testing.T) {
		outputPath := filepath.Join(t.TempDir(), "out.txt")
		if err := gen.executeTemplate("copyright", outputPath, map[string]interface{}{"Template": "custom.tmpl"}); err != nil {
			t.Fatalf("executeTemplate(map): %v", err)
		}

		gotBytes, err := os.ReadFile(outputPath)
		if err != nil {
			t.Fatalf("ReadFile: %v", err)
		}

		want := strings.Join([]string{"test", "custom.tmpl", strconv.Itoa(time.Now().UTC().Year())}, "|")
		if got := strings.TrimSpace(string(gotBytes)); got != want {
			t.Fatalf("executeTemplate(map) = %q, want %q", got, want)
		}
	})
}

func TestWriteGeneratedFileSkipsTimestampOnlyChanges(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated.go")
	original := []byte("// Code generated by Fabrica v0.4.2. DO NOT EDIT.\n// Generated: 2026-05-05T00:00:00Z\npackage test\n")
	updated := []byte("// Code generated by Fabrica v0.4.3-dirty. DO NOT EDIT.\n// Generated: 2026-05-05T00:00:01Z\npackage test\n")

	written, err := writeGeneratedFile(path, original)
	if err != nil {
		t.Fatalf("writeGeneratedFile(original): %v", err)
	}
	if !written {
		t.Fatal("expected initial write to write content")
	}

	written, err = writeGeneratedFile(path, updated)
	if err != nil {
		t.Fatalf("writeGeneratedFile(updated): %v", err)
	}
	if written {
		t.Fatal("expected timestamp-only change to be skipped")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !bytes.Equal(got, original) {
		t.Fatalf("file content changed unexpectedly: got %q want %q", got, original)
	}
}

func TestWriteGeneratedFileWritesRealChanges(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated.go")
	original := []byte("// Code generated by Fabrica v0.4.2. DO NOT EDIT.\n// Generated: 2026-05-05T00:00:00Z\npackage test\n")
	updated := []byte("// Code generated by Fabrica v0.4.3-dirty. DO NOT EDIT.\n// Generated: 2026-05-05T00:00:01Z\npackage test\n\nfunc x() {}\n")

	if _, err := writeGeneratedFile(path, original); err != nil {
		t.Fatalf("writeGeneratedFile(original): %v", err)
	}

	written, err := writeGeneratedFile(path, updated)
	if err != nil {
		t.Fatalf("writeGeneratedFile(updated): %v", err)
	}
	if !written {
		t.Fatal("expected real change to be written")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !bytes.Equal(got, updated) {
		t.Fatalf("file content mismatch: got %q want %q", got, updated)
	}
}
