// SPDX-FileCopyrightText: © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"text/template"
	"time"
)

func TestTemplateDataIncludesCopyrightYear(t *testing.T) {
	gen := NewGenerator(t.TempDir(), "main", "example.com/test")
	gen.Version = "test"

	resource := ResourceMetadata{
		Name:         "Node",
		PluralName:   "nodes",
		Package:      "example.com/test/pkg/resources/node",
		PackageAlias: "node",
		TypeName:     "*node.Node",
		SpecType:     "node.NodeSpec",
		StatusType:   "node.NodeStatus",
		URLPath:      "/nodes",
		StorageName:  "Node",
	}

	data := gen.templateData(resource, "server/handlers.go.tmpl")
	if got, ok := data["CopyrightYear"].(int); !ok || got != time.Now().UTC().Year() {
		t.Fatalf("templateData CopyrightYear = %v, want %d", data["CopyrightYear"], time.Now().UTC().Year())
	}
}

func TestGlobalAndMiddlewareTemplateDataIncludeCopyrightYear(t *testing.T) {
	gen := NewGenerator(t.TempDir(), "main", "example.com/test")
	gen.Version = "test"

	for name, data := range map[string]map[string]interface{}{
		"global":     gen.globalTemplateData("server/models.go.tmpl"),
		"middleware": gen.middlewareData("middleware/validation.go.tmpl"),
	} {
		if got, ok := data["CopyrightYear"].(int); !ok || got != time.Now().UTC().Year() {
			t.Fatalf("%s CopyrightYear = %v, want %d", name, data["CopyrightYear"], time.Now().UTC().Year())
		}
	}
}

func TestGenerateClientUsesPerClientTokenVisibility(t *testing.T) {
	outDir := t.TempDir()
	gen := NewGenerator(outDir, "client", "example.com/test")
	gen.Resources = []ResourceMetadata{
		{
			Name:         "Node",
			PluralName:   "nodes",
			Package:      "example.com/test/apis/v1",
			PackageAlias: "v1",
			TypeName:     "*v1.Node",
			SpecType:     "v1.NodeSpec",
			StatusType:   "v1.NodeStatus",
			URLPath:      "/nodes",
			StorageName:  "Node",
		},
	}

	if err := gen.LoadTemplates(); err != nil {
		t.Fatalf("LoadTemplates: %v", err)
	}
	if err := gen.GenerateClient(); err != nil {
		t.Fatalf("GenerateClient: %v", err)
	}

	generated, err := os.ReadFile(filepath.Join(outDir, "client_generated.go"))
	if err != nil {
		t.Fatalf("read generated client: %v", err)
	}
	client := string(generated)

	if !regexp.MustCompile(`showToken\s+bool\s+// Whether access tokens`).MatchString(client) {
		t.Error("generated client missing per-client token visibility field")
	}
	for _, want := range []string{
		"func (c *Client) WithShowToken(show bool) *Client",
		"redactAuthHeaderValues(v, c.showToken)",
	} {
		if !strings.Contains(client, want) {
			t.Errorf("generated client missing %q", want)
		}
	}
	if strings.Contains(client, "var ShowToken bool") {
		t.Error("generated client contains package-global token visibility state")
	}
}

func TestExecuteTemplateBackfillsCommonMetadata(t *testing.T) {
	gen := NewGenerator(t.TempDir(), "main", "example.com/test")
	gen.Version = "test"
	gen.Templates = map[string]*template.Template{
		"copyright": template.Must(template.New("copyright").Parse("{{.Version}}|{{.Template}}|{{.CopyrightYear}}")),
	}

	t.Run("nil data", func(t *testing.T) {
		outputPath := filepath.Join(t.TempDir(), "out.txt")
		if err := gen.executeTemplate("copyright", outputPath, nil); err != nil {
			t.Fatalf("executeTemplate(nil): %v", err)
		}

		gotBytes, err := os.ReadFile(outputPath)
		if err != nil {
			t.Fatalf("ReadFile: %v", err)
		}

		want := strings.Join([]string{"test", "copyright", strconv.Itoa(time.Now().UTC().Year())}, "|")
		if got := strings.TrimSpace(string(gotBytes)); got != want {
			t.Fatalf("executeTemplate(nil) = %q, want %q", got, want)
		}
	})

	t.Run("map data", func(t *testing.T) {
		outputPath := filepath.Join(t.TempDir(), "out.txt")
		if err := gen.executeTemplate("copyright", outputPath, map[string]interface{}{"Template": "custom.tmpl"}); err != nil {
			t.Fatalf("executeTemplate(map): %v", err)
		}

		gotBytes, err := os.ReadFile(outputPath)
		if err != nil {
			t.Fatalf("ReadFile: %v", err)
		}

		want := strings.Join([]string{"test", "custom.tmpl", strconv.Itoa(time.Now().UTC().Year())}, "|")
		if got := strings.TrimSpace(string(gotBytes)); got != want {
			t.Fatalf("executeTemplate(map) = %q, want %q", got, want)
		}
	})
}

func TestWriteGeneratedFileSkipsTimestampOnlyChanges(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated.go")
	original := []byte("// Code generated by Fabrica v0.4.2. DO NOT EDIT.\n// Generated: 2026-05-05T00:00:00Z\npackage test\n")
	updated := []byte("// Code generated by Fabrica v0.4.3-dirty (commit: deadbeef). DO NOT EDIT.\n// Generated: 2026-05-05T00:00:01Z\npackage test\n")

	written, err := writeGeneratedFile(path, original)
	if err != nil {
		t.Fatalf("writeGeneratedFile(original): %v", err)
	}
	if !written {
		t.Fatal("expected initial write to write content")
	}

	written, err = writeGeneratedFile(path, updated)
	if err != nil {
		t.Fatalf("writeGeneratedFile(updated): %v", err)
	}
	if written {
		t.Fatal("expected timestamp-only change to be skipped")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !bytes.Equal(got, original) {
		t.Fatalf("file content changed unexpectedly: got %q want %q", got, original)
	}
}

func TestWriteGeneratedFileWritesRealChanges(t *testing.T) {
	path := filepath.Join(t.TempDir(), "generated.go")
	original := []byte("// Code generated by Fabrica v0.4.2. DO NOT EDIT.\n// Generated: 2026-05-05T00:00:00Z\npackage test\n")
	updated := []byte("// Code generated by Fabrica v0.4.3-dirty. DO NOT EDIT.\n// Generated: 2026-05-05T00:00:01Z\npackage test\n\nfunc x() {}\n")

	if _, err := writeGeneratedFile(path, original); err != nil {
		t.Fatalf("writeGeneratedFile(original): %v", err)
	}

	written, err := writeGeneratedFile(path, updated)
	if err != nil {
		t.Fatalf("writeGeneratedFile(updated): %v", err)
	}
	if !written {
		t.Fatal("expected real change to be written")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !bytes.Equal(got, updated) {
		t.Fatalf("file content mismatch: got %q want %q", got, updated)
	}
}

func TestGenerateStorageSkipsCustomStorage(t *testing.T) {
	dir := t.TempDir()
	gen := NewGenerator(dir, "main", "example.com/test")
	gen.SetStorageType("custom")

	if err := gen.LoadTemplates(); err != nil {
		t.Fatalf("LoadTemplates: %v", err)
	}
	if err := gen.GenerateStorage(); err != nil {
		t.Fatalf("GenerateStorage: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "internal", "storage", "storage_generated.go")); !os.IsNotExist(err) {
		t.Fatalf("custom storage generated storage file, stat err=%v", err)
	}
}
