// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestManagedSchemaOutput_pre_swap_faults_leave_current_tree_unchanged(t *testing.T) {
	tests := []struct {
		name  string
		fault func(*managedSchemaOperations)
	}{
		{name: "staging", fault: func(ops *managedSchemaOperations) {
			mkdirAll := ops.mkdirAll
			ops.mkdirAll = func(path string, mode os.FileMode) error {
				if strings.Contains(path, ".fabrica-staging.") {
					return errors.New("staging fault")
				}
				return mkdirAll(path, mode)
			}
		}},
		{name: "render", fault: func(ops *managedSchemaOperations) {
			ops.render = func(string, interface{}) ([]byte, error) { return nil, errors.New("render fault") }
		}},
		{name: "format", fault: func(ops *managedSchemaOperations) {
			ops.format = func([]byte) ([]byte, error) { return nil, errors.New("format fault") }
		}},
		{name: "write", fault: func(ops *managedSchemaOperations) {
			writeFile := ops.writeFile
			ops.writeFile = func(path string, content []byte, mode os.FileMode) error {
				if filepath.Ext(path) == ".go" {
					return errors.New("write fault")
				}
				return writeFile(path, content, mode)
			}
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Given
			root := t.TempDir()
			current := filepath.Join(root, "schema")
			writeManagedSchemaFixture(t, filepath.Join(current, "resource.go"), "type Before struct{}")
			before := snapshotAtomicTree(t, current)
			ops := newManagedSchemaOperations(func(string, interface{}) ([]byte, error) {
				return []byte("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype After struct{}\n"), nil
			})
			tt.fault(&ops)
			output := newManagedSchemaOutput(current, ops)

			// When
			err := output.commit([]managedSchemaFile{{name: "resource.go", templateName: "resource"}})

			// Then
			if err == nil {
				t.Fatal("commit() error = nil")
			}
			if after := snapshotAtomicTree(t, current); !reflect.DeepEqual(before, after) {
				t.Fatalf("current tree changed\nbefore: %#v\nafter: %#v", before, after)
			}
		})
	}
}

func TestManagedSchemaOutput_recovery_keeps_current_and_discards_orphaned_transaction_trees(t *testing.T) {
	// Given
	root := t.TempDir()
	current := filepath.Join(root, "schema")
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))
	writeManagedSchemaFixture(t, filepath.Join(current, "resource.go"), "type Current struct{}")
	output.canonical = canonicalSchemaRootForTest(t, output)
	writeTransactionArtifactFixture(t, output.backup, output.expectedManifest(transactionRoleBackup, output.transactionID))
	writeTransactionArtifactFixture(t, output.staging, output.expectedManifest(transactionRoleStaging, output.transactionID))
	writeManagedSchemaFixture(t, filepath.Join(output.backupTree(), "resource.go"), "type Backup struct{}")
	writeManagedSchemaFixture(t, filepath.Join(output.stagingTree(), "resource.go"), "type Staging struct{}")
	before := snapshotAtomicTree(t, current)

	// When
	err := output.recover()

	// Then
	if err != nil {
		t.Fatalf("recover() error = %v", err)
	}
	if after := snapshotAtomicTree(t, current); !reflect.DeepEqual(before, after) {
		t.Fatalf("current tree changed\nbefore: %#v\nafter: %#v", before, after)
	}
	if _, err := os.Stat(output.backup); !os.IsNotExist(err) {
		t.Fatalf("orphaned backup remains: %v", err)
	}
	if _, err := os.Stat(output.staging); !os.IsNotExist(err) {
		t.Fatalf("orphaned staging remains: %v", err)
	}
}

func TestManagedSchemaOutput_swap_faults_restore_current_tree(t *testing.T) {
	for _, failedRename := range []int{1, 2} {
		t.Run(string(rune('0'+failedRename)), func(t *testing.T) {
			// Given
			root := t.TempDir()
			current := filepath.Join(root, "schema")
			writeManagedSchemaFixture(t, filepath.Join(current, "resource.go"), "type Before struct{}")
			before := snapshotAtomicTree(t, current)
			ops := newManagedSchemaOperations(func(string, interface{}) ([]byte, error) {
				return []byte("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype After struct{}\n"), nil
			})
			output := newManagedSchemaOutput(current, ops)
			rename := output.ops.rename
			output.ops.rename = func(oldPath, newPath string) error {
				firstSwap := oldPath == output.current && newPath == output.backupTree()
				secondSwap := oldPath == output.stagingTree() && newPath == output.current
				if (failedRename == 1 && firstSwap) || (failedRename == 2 && secondSwap) {
					return errors.New("rename fault")
				}
				return rename(oldPath, newPath)
			}

			// When
			err := output.commit([]managedSchemaFile{{name: "resource.go", templateName: "resource"}})

			// Then
			if err == nil {
				t.Fatal("commit() error = nil")
			}
			if after := snapshotAtomicTree(t, current); !reflect.DeepEqual(before, after) {
				t.Fatalf("current tree changed\nbefore: %#v\nafter: %#v", before, after)
			}
		})
	}
}

func TestManagedSchemaOutput_interrupted_rollback_recovers_on_next_run(t *testing.T) {
	// Given
	root := t.TempDir()
	current := filepath.Join(root, "schema")
	writeManagedSchemaFixture(t, filepath.Join(current, "resource.go"), "type Before struct{}")
	before := snapshotAtomicTree(t, current)
	ops := newManagedSchemaOperations(func(string, interface{}) ([]byte, error) {
		return []byte("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype After struct{}\n"), nil
	})
	output := newManagedSchemaOutput(current, ops)
	rename := output.ops.rename
	output.ops.rename = func(oldPath, newPath string) error {
		install := oldPath == output.stagingTree() && newPath == output.current
		rollback := oldPath == output.backupTree() && newPath == output.current
		if install || rollback {
			return errors.New("rename fault")
		}
		return rename(oldPath, newPath)
	}
	if err := output.commit([]managedSchemaFile{{name: "resource.go", templateName: "resource"}}); err == nil {
		t.Fatal("commit() error = nil")
	}

	// When
	recovery := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))
	err := recovery.recover()

	// Then
	if err != nil {
		t.Fatalf("recover() error = %v", err)
	}
	if after := snapshotAtomicTree(t, current); !reflect.DeepEqual(before, after) {
		t.Fatalf("recovered tree differs\nbefore: %#v\nafter: %#v", before, after)
	}
}
