// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func TestManagedSchemaHeader_requires_exact_first_line(t *testing.T) {
	tests := []struct {
		name    string
		content string
		managed bool
	}{
		{name: "exact", content: "// Code generated by Fabrica. DO NOT EDIT.\npackage schema\n", managed: true},
		{name: "version spoof", content: "// Code generated by Fabrica v9.9.9. DO NOT EDIT.\npackage schema\n"},
		{name: "suffix spoof", content: "// Code generated by Fabrica. DO NOT EDIT. extra\npackage schema\n"},
		{name: "prefix only", content: "// Code generated by Fabrica\npackage schema\n"},
		{name: "leading blank", content: "\n// Code generated by Fabrica. DO NOT EDIT.\npackage schema\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isFabricaManagedSchema([]byte(tt.content)); got != tt.managed {
				t.Fatalf("isFabricaManagedSchema() = %t, want %t", got, tt.managed)
			}
		})
	}
}

func TestManagedSchemaOutput_uses_unique_transaction_artifact_names(t *testing.T) {
	// Given
	current := filepath.Join(t.TempDir(), "schema")
	first := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))
	second := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))

	// When
	sameStaging := first.staging == second.staging
	sameBackup := first.backup == second.backup

	// Then
	if sameStaging || sameBackup || first.transactionID == second.transactionID {
		t.Fatalf("transaction identities collide: %#v %#v", first, second)
	}
}

func TestManagedSchemaOutput_recovery_rejects_manifest_identity_mismatch(t *testing.T) {
	tests := []struct {
		name   string
		mutate func(*transactionManifest)
	}{
		{name: "version", mutate: func(manifest *transactionManifest) { manifest.Version++ }},
		{name: "canonical root", mutate: func(manifest *transactionManifest) { manifest.CanonicalRoot += "-other" }},
		{name: "transaction identity", mutate: func(manifest *transactionManifest) { manifest.TransactionID = "other" }},
		{name: "role", mutate: func(manifest *transactionManifest) { manifest.Role = transactionRoleBackup }},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Given
			current := filepath.Join(t.TempDir(), "schema")
			writeManagedSchemaFixture(t, filepath.Join(current, "resource.go"), "type Current struct{}")
			output := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))
			output.canonical = canonicalSchemaRootForTest(t, output)
			manifest := output.expectedManifest(transactionRoleStaging, output.transactionID)
			tt.mutate(&manifest)
			writeTransactionArtifactFixture(t, output.staging, manifest)
			manifestBefore, err := os.ReadFile(filepath.Join(output.staging, transactionManifestName))
			if err != nil {
				t.Fatal(err)
			}

			// When
			err = output.recover()

			// Then
			if !errors.Is(err, errUnmanagedSchemaPath) {
				t.Fatalf("recover() error = %v, want identity error", err)
			}
			manifestAfter, readErr := os.ReadFile(filepath.Join(output.staging, transactionManifestName))
			if readErr != nil || string(manifestAfter) != string(manifestBefore) {
				t.Fatalf("ambiguous artifact changed = %q, %v", manifestAfter, readErr)
			}
		})
	}
}

func TestManagedSchemaOutput_recovery_rejects_malformed_manifest(t *testing.T) {
	// Given
	current := filepath.Join(t.TempDir(), "schema")
	writeManagedSchemaFixture(t, filepath.Join(current, "resource.go"), "type Current struct{}")
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))
	if err := os.MkdirAll(output.staging, 0o700); err != nil {
		t.Fatal(err)
	}
	malformed, err := json.Marshal(map[string]string{"version": "spoof"})
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(output.staging, transactionManifestName), malformed, 0o600); err != nil {
		t.Fatal(err)
	}

	// When
	err = output.recover()

	// Then
	if !errors.Is(err, errUnmanagedSchemaPath) {
		t.Fatalf("recover() error = %v, want malformed manifest error", err)
	}
	if _, err := os.Stat(output.staging); err != nil {
		t.Fatalf("malformed artifact was changed: %v", err)
	}
}

func TestManagedSchemaOutput_rejects_schema_root_symlink_without_touching_target(t *testing.T) {
	// Given
	root := t.TempDir()
	target := filepath.Join(root, "target")
	writeSchemaFixture(t, filepath.Join(target, "custom.go"), "package schema\ntype Custom struct{}\n")
	before := snapshotAtomicTree(t, target)
	current := filepath.Join(root, "schema")
	if err := os.Symlink(target, current); err != nil {
		t.Fatal(err)
	}
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(func(string, interface{}) ([]byte, error) {
		return []byte("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype Generated struct{}\n"), nil
	}))

	// When
	err := output.commit([]managedSchemaFile{{name: "resource.go", templateName: "resource"}})

	// Then
	if !errors.Is(err, errUnmanagedSchemaPath) {
		t.Fatalf("commit() error = %v, want protected-root error", err)
	}
	if after := snapshotAtomicTree(t, target); !reflect.DeepEqual(before, after) {
		t.Fatalf("symlink target changed\nbefore: %#v\nafter: %#v", before, after)
	}
	if info, statErr := os.Lstat(current); statErr != nil || info.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("schema root symlink changed: %#v, %v", info, statErr)
	}
}

func TestManagedSchemaOutput_spoof_header_remains_unmanaged_and_blocks_overwrite(t *testing.T) {
	// Given
	current := filepath.Join(t.TempDir(), "schema")
	path := filepath.Join(current, "resource.go")
	before := []byte("// Code generated by Fabrica v9.9.9. DO NOT EDIT.\npackage schema\ntype Spoof struct{}\n")
	writeSchemaFixture(t, path, string(before))
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(func(string, interface{}) ([]byte, error) {
		return []byte("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype Managed struct{}\n"), nil
	}))

	// When
	err := output.commit([]managedSchemaFile{{name: "resource.go", templateName: "resource"}})

	// Then
	if !errors.Is(err, errUnmanagedSchemaPath) {
		t.Fatalf("commit() error = %v, want unmanaged conflict", err)
	}
	after, readErr := os.ReadFile(path)
	if readErr != nil || string(after) != string(before) {
		t.Fatalf("spoof header file changed = %q, %v", after, readErr)
	}
}

func TestManagedSchemaOutput_recovery_refuses_unmanaged_near_name_directory(t *testing.T) {
	// Given
	root := t.TempDir()
	current := filepath.Join(root, "schema")
	writeManagedSchemaFixture(t, filepath.Join(current, "resource.go"), "type Current struct{}")
	nearName := current + ".fabrica-staging"
	writeSchemaFixture(t, filepath.Join(nearName, "sentinel"), "unmanaged")
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))

	// When
	err := output.recover()

	// Then
	if !errors.Is(err, errUnmanagedSchemaPath) {
		t.Fatalf("recover() error = %v, want unmanaged-artifact error", err)
	}
	if content, readErr := os.ReadFile(filepath.Join(nearName, "sentinel")); readErr != nil || string(content) != "unmanaged" {
		t.Fatalf("near-name directory changed = %q, %v", content, readErr)
	}
}
