// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestManagedSchemaOutput_success_replaces_managed_tree_and_preserves_unmanaged_entries(t *testing.T) {
	// Given
	root := t.TempDir()
	current := filepath.Join(root, "schema")
	writeManagedSchemaFixture(t, filepath.Join(current, "stale.go"), "type Stale struct{}")
	writeSchemaFixture(t, filepath.Join(current, "custom.go"), "package schema\ntype Custom struct{}\n")
	linkTarget := filepath.Join(root, "external.go")
	writeSchemaFixture(t, linkTarget, "package external\n")
	if err := os.Symlink(linkTarget, filepath.Join(current, "linked.go")); err != nil {
		t.Fatalf("create unmanaged symlink: %v", err)
	}
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(func(templateName string, _ interface{}) ([]byte, error) {
		return []byte("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype " + templateName + " struct{}\n"), nil
	}))

	// When
	err := output.commit([]managedSchemaFile{{name: "resource.go", templateName: "Resource"}})

	// Then
	if err != nil {
		t.Fatalf("commit() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(current, "stale.go")); !os.IsNotExist(err) {
		t.Fatalf("stale managed schema remains: %v", err)
	}
	if content, err := os.ReadFile(filepath.Join(current, "custom.go")); err != nil || string(content) != "package schema\ntype Custom struct{}\n" {
		t.Fatalf("unmanaged schema = %q, %v", content, err)
	}
	if target, err := os.Readlink(filepath.Join(current, "linked.go")); err != nil || target != linkTarget {
		t.Fatalf("unmanaged symlink = %q, %v", target, err)
	}
	if content, err := os.ReadFile(filepath.Join(current, "resource.go")); err != nil || !isFabricaManagedSchema(content) {
		t.Fatalf("managed resource schema = %q, %v", content, err)
	}
}

func TestManagedSchemaOutput_semantic_failure_quarantines_only_prior_managed_resource(t *testing.T) {
	// Given
	root := t.TempDir()
	current := filepath.Join(root, "schema")
	managed := filepath.Join(current, "token.go")
	unmanaged := filepath.Join(current, "device.go")
	writeManagedSchemaFixture(t, managed, "type Token struct{}")
	writeSchemaFixture(t, unmanaged, "package schema\ntype Device struct{}\n")
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))

	// When
	err := output.quarantine("token.go")

	// Then
	if err != nil {
		t.Fatalf("quarantine() error = %v", err)
	}
	if _, err := os.Stat(managed); !os.IsNotExist(err) {
		t.Fatalf("managed schema remains active: %v", err)
	}
	quarantine := filepath.Join(output.quarantineArtifact, "token.go")
	if content, err := os.ReadFile(quarantine); err != nil || !isFabricaManagedSchema(content) {
		t.Fatalf("quarantined schema = %q, %v", content, err)
	}
	if content, err := os.ReadFile(unmanaged); err != nil || string(content) != "package schema\ntype Device struct{}\n" {
		t.Fatalf("unmanaged schema changed = %q, %v", content, err)
	}
}

func findTransactionArtifactFixture(t *testing.T, current string, role transactionRole) string {
	t.Helper()
	prefix := filepath.Base(current) + ".fabrica-" + string(role) + "."
	entries, err := os.ReadDir(filepath.Dir(current))
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), prefix) {
			return filepath.Join(filepath.Dir(current), entry.Name())
		}
	}
	t.Fatalf("transaction artifact with role %s not found", role)
	return ""
}

func TestManagedSchemaOutput_quarantine_preserves_unmanaged_and_symlink_paths(t *testing.T) {
	tests := []struct {
		name string
		make func(*testing.T, string)
	}{
		{name: "unmanaged regular file", make: func(t *testing.T, path string) { writeSchemaFixture(t, path, "package schema\n") }},
		{name: "symlink", make: func(t *testing.T, path string) {
			target := filepath.Join(t.TempDir(), "target.go")
			writeManagedSchemaFixture(t, target, "type Target struct{}")
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.Symlink(target, path); err != nil {
				t.Fatal(err)
			}
		}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Given
			current := filepath.Join(t.TempDir(), "schema")
			path := filepath.Join(current, "token.go")
			tt.make(t, path)
			output := newManagedSchemaOutput(current, newManagedSchemaOperations(nil))

			// When
			err := output.quarantine("token.go")

			// Then
			if !errors.Is(err, errUnmanagedSchemaPath) {
				t.Fatalf("quarantine() error = %v", err)
			}
			if _, err := os.Lstat(path); err != nil {
				t.Fatalf("protected path changed: %v", err)
			}
		})
	}
}

func writeManagedSchemaFixture(t *testing.T, path, declaration string) {
	t.Helper()
	writeSchemaFixture(t, path, "// Code generated by Fabrica. DO NOT EDIT.\npackage schema\n"+declaration+"\n")
}

func writeSchemaFixture(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
