// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package codegen

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"
)

const schemaHelperEnv = "FABRICA_MANAGED_SCHEMA_HELPER"

func TestManagedSchemaSubprocessHelper(_ *testing.T) {
	if os.Getenv(schemaHelperEnv) != "1" {
		return
	}
	current := os.Getenv("FABRICA_SCHEMA_ROOT")
	start := os.Getenv("FABRICA_SCHEMA_START")
	ready := os.Getenv("FABRICA_SCHEMA_READY")
	releasePath := os.Getenv("FABRICA_SCHEMA_RELEASE")
	result := os.Getenv("FABRICA_SCHEMA_RESULT")
	identity := os.Getenv("FABRICA_SCHEMA_ID")
	mode := os.Getenv("FABRICA_SCHEMA_MODE")
	boundary := os.Getenv("FABRICA_SCHEMA_CRASH_BOUNDARY")
	if start != "" {
		if err := waitForSchemaHelperPath(start); err != nil {
			writeSchemaHelperResult(result, "error:"+err.Error())
			return
		}
	}
	output := newManagedSchemaOutput(current, newManagedSchemaOperations(func(string, interface{}) ([]byte, error) {
		content := fmt.Sprintf("// Code generated by Fabrica. DO NOT EDIT.\npackage schema\ntype Owner%s struct{}\n", identity)
		return []byte(content), nil
	}))
	if boundary != "" {
		rename := output.ops.rename
		output.ops.rename = func(oldPath, newPath string) error {
			first := boundary == "first" && oldPath == output.current && newPath == output.backupTree()
			second := boundary == "second" && oldPath == output.stagingTree() && newPath == output.current
			if err := rename(oldPath, newPath); err != nil {
				return err
			}
			if first || second {
				if err := os.WriteFile(ready, []byte(identity), 0o600); err != nil {
					writeSchemaHelperResult(result, "error:"+err.Error())
				}
				os.Exit(91)
			}
			return nil
		}
	}
	release, err := output.acquireTransactionLock()
	if err != nil {
		switch {
		case errors.Is(err, ErrManagedSchemaBusy):
			writeSchemaHelperResult(result, "busy")
		default:
			writeSchemaHelperResult(result, "error:"+err.Error())
		}
		return
	}
	status := "owner"
	if err := output.recoverLocked(); err != nil {
		status = "error:" + err.Error()
	} else if mode == "crash-lock" {
		if err := os.WriteFile(ready, []byte(identity), 0o600); err != nil {
			writeSchemaHelperResult(result, "error:"+err.Error())
			return
		}
		if err := waitForSchemaHelperPath(releasePath); err != nil {
			writeSchemaHelperResult(result, "error:"+err.Error())
		}
		return
	} else if err := os.WriteFile(ready, []byte(identity), 0o600); err != nil && !os.IsExist(err) {
		status = "error:" + err.Error()
	} else if err := waitForSchemaHelperPath(releasePath); err != nil {
		status = "error:" + err.Error()
	} else if err := output.commitLocked([]managedSchemaFile{{name: "resource.go", templateName: "resource"}}); err != nil {
		status = "error:" + err.Error()
	}
	if err := release(); err != nil && status == "owner" {
		status = "error:" + err.Error()
	}
	writeSchemaHelperResult(result, status)
}

func waitForSchemaHelperPath(path string) error {
	deadline := time.Now().Add(15 * time.Second)
	for time.Now().Before(deadline) {
		if _, err := os.Stat(path); err == nil {
			return nil
		} else if !os.IsNotExist(err) {
			return err
		}
		time.Sleep(5 * time.Millisecond)
	}
	return fmt.Errorf("timeout waiting for %s", filepath.Base(path))
}

func writeSchemaHelperResult(path, status string) {
	if err := os.WriteFile(path, []byte(status), 0o600); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "write helper result: %v\n", err)
	}
}
