// SPDX-FileCopyrightText: 2026 Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package integration

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/suite"
)

// VersionCommandTestSuite tests that generated services have a working version command
type VersionCommandTestSuite struct {
	suite.Suite
	fabricaBinary string
	tempDir       string
	projects      []*TestProject
}

func (s *VersionCommandTestSuite) SetupSuite() {
	wd, err := os.Getwd()
	s.Require().NoError(err)

	projectRoot := filepath.Join(wd, "..", "..")
	s.fabricaBinary = filepath.Join(projectRoot, "bin", "fabrica")
	s.Require().FileExists(s.fabricaBinary, "fabrica binary must be built")

	s.fabricaBinary, err = filepath.Abs(s.fabricaBinary)
	s.Require().NoError(err)

	s.tempDir = s.T().TempDir()
}

func (s *VersionCommandTestSuite) TearDownTest() {
	for _, project := range s.projects {
		project.StopServer() //nolint:all
	}
	s.projects = nil
}

func (s *VersionCommandTestSuite) createProject(name, module, storage string) *TestProject {
	project := NewTestProject(&s.Suite, s.tempDir, name, module, storage)
	s.projects = append(s.projects, project)
	return project
}

// TestVersionCommandGenerated verifies that a version command is generated and works
func (s *VersionCommandTestSuite) TestVersionCommandGenerated() {
	project := s.createProject("version-test", "github.com/test/version", "file")

	err := project.InitializeWithFlags(s.fabricaBinary, "--version")
	s.Require().NoError(err)

	err = project.AddResource(s.fabricaBinary, "Device")
	s.Require().NoError(err)

	err = project.Generate(s.fabricaBinary)
	s.Require().NoError(err)

	serverBinary := filepath.Join(project.Dir, "server-binary")
	buildCmd := exec.Command("go", "build", "-o", serverBinary, "./cmd/server")
	buildCmd.Dir = project.Dir
	buildOutput, err := buildCmd.CombinedOutput()
	s.Require().NoError(err, "Server binary should compile successfully: %s", buildOutput)

	cmd := exec.Command(serverBinary, "version")
	cmd.Dir = project.Dir
	output, err := cmd.CombinedOutput()
	s.Require().NoError(err, "version command should execute successfully")

	outputStr := string(output)
	s.Require().Contains(outputStr, "version", "version output should contain 'version'")
	s.Require().Contains(outputStr, "generated by: Fabrica", "version output should show Fabrica generator version")
}

// TestVersionCommandShowsBothVersions verifies service and Fabrica versions are both displayed
func (s *VersionCommandTestSuite) TestVersionCommandShowsBothVersions() {
	project := s.createProject("version-both-test", "github.com/test/version-both", "file")

	err := project.InitializeWithFlags(s.fabricaBinary, "--version")
	s.Require().NoError(err)

	err = project.AddResource(s.fabricaBinary, "Task")
	s.Require().NoError(err)

	err = project.Generate(s.fabricaBinary)
	s.Require().NoError(err)

	serverBinary := filepath.Join(project.Dir, "server-binary")
	buildCmd := exec.Command("go", "build", "-o", serverBinary, "./cmd/server")
	buildCmd.Dir = project.Dir
	buildOutput, err := buildCmd.CombinedOutput()
	s.Require().NoError(err, "Server binary should compile successfully: %s", buildOutput)

	cmd := exec.Command(serverBinary, "version")
	cmd.Dir = project.Dir
	output, err := cmd.CombinedOutput()
	s.Require().NoError(err)

	outputStr := string(output)

	s.Require().Contains(outputStr, "version", "version output should contain version information")
	s.Require().Contains(outputStr, "generated by: Fabrica", "version output should show generator version")
}

// TestVersionCommandNotGeneratedWhenDisabled verifies version command can be disabled
func (s *VersionCommandTestSuite) TestVersionCommandNotGeneratedWhenDisabled() {
	project := s.createProject("version-disabled-test", "github.com/test/version-disabled", "file")

	err := project.InitializeWithFlags(s.fabricaBinary, "--version=false")
	s.Require().NoError(err)

	err = project.AddResource(s.fabricaBinary, "Widget")
	s.Require().NoError(err)

	err = project.Generate(s.fabricaBinary)
	s.Require().NoError(err)

	serverBinary := filepath.Join(project.Dir, "server-binary")
	buildCmd := exec.Command("go", "build", "-o", serverBinary, "./cmd/server")
	buildCmd.Dir = project.Dir
	buildOutput, err := buildCmd.CombinedOutput()
	s.Require().NoError(err, "Server binary should compile successfully: %s", buildOutput)

	cmd := exec.Command(serverBinary, "version")
	cmd.Dir = project.Dir
	output, err := cmd.CombinedOutput()

	s.Require().Error(err, "version command should not exist when disabled")
	s.Require().Contains(string(output), "unknown command", "output should indicate version command doesn't exist")
}

func TestVersionCommandSuite(t *testing.T) {
	suite.Run(t, new(VersionCommandTestSuite))
}
